import 'package:flutter/material.dart';

import 'colors.dart';
import 'color_constants.dart';
import 'text_theme.dart'; // TODO: Bring in typography into CarbonTokens

class CarbonTokens {
  static const white = CarbonColorTokens(
    background: carbonWhite,
    backgroundHover: Color.fromRGBO(
      141,
      141,
      141,
      .12,
    ), // carbonGray50 with 12% opacity
    backgroundActive: Color.fromRGBO(
      141,
      141,
      141,
      .50,
    ), // carbonGray50 with 50% opacity
    backgroundSelected: Color.fromRGBO(
      141,
      141,
      141,
      .20,
    ), // carbonGray50 with 20% opacity
    backgroundSelectedHover: Color.fromRGBO(
      141,
      141,
      141,
      .32,
    ), // carbonGray50 with 32% opacity
    backgroundInverse: carbonGray80,
    backgroundInverseHover: carbonGrayHover80,
    backgroundBrand: carbonBlue60,
    layer01: carbonGray10,
    layer02: carbonWhite,
    layer03: carbonGray10,
    layerHover01: carbonGrayHover10,
    layerHover02: carbonGrayHover10,
    layerHover03: carbonGrayHover10,
    layerActive01: carbonGray30,
    layerActive02: carbonGray30,
    layerActive03: carbonGray30,
    layerSelected01: carbonGray20,
    layerSelected02: carbonGray20,
    layerSelected03: carbonGray20,
    layerSelectedHover01: carbonGrayHover20,
    layerSelectedHover02: carbonGrayHover20,
    layerSelectedHover03: carbonGrayHover20,
    layerSelectedInverse: carbonGray100,
    layerSelectedDisabled: Color.from(
      alpha: 1,
      red: 0.553,
      green: 0.553,
      blue: 0.553,
    ),
    layerAccent01: carbonGray20,
    layerAccent02: carbonGray20,
    layerAccent03: carbonGray20,
    layerAccentHover01: carbonGrayHover20,
    layerAccentHover02: carbonGrayHover20,
    layerAccentHover03: carbonGrayHover20,
    layerAccentActive01: carbonGray40,
    layerAccentActive02: carbonGray40,
    layerAccentActive03: carbonGray40,
    field01: carbonGray10,
    field02: carbonWhite,
    field03: carbonGray10,
    fieldHover01: carbonGrayHover10,
    fieldHover02: carbonGrayHover10,
    fieldHover03: carbonGrayHover10,
    borderInteractive: carbonBlue60,
    borderSubtle00: carbonGray20,
    borderSubtle01: carbonGray30,
    borderSubtle02: carbonGray20,
    borderSubtle03: carbonGray30,
    borderSubtleSelected01: carbonGray30,
    borderSubtleSelected02: carbonGray30,
    borderSubtleSelected03: carbonGray30,
    borderStrong01: carbonGray50,
    borderStrong02: carbonGray50,
    borderStrong03: carbonGray50,
    borderTitle01: carbonGray30,
    borderTitle02: carbonGray40,
    borderTitle03: carbonGray30,
    borderInverse: carbonGray100,
    borderDisabled: carbonGray30,
    textPrimary: carbonGray100,
    textSecondary: carbonGray70,
    textPlaceholder: carbonGray40,
    textOnColor: carbonWhite,
    textOnColorDisabled: carbonGray50,
    textHelper: carbonGray60,
    textError: carbonRed60,
    textInverse: carbonWhite,
    textDisabled: Color.fromRGBO(
      22,
      22,
      22,
      .25,
    ), // carbonGray100 with 25% opacity
    linkPrimary: carbonBlue60,
    linkPrimaryHover: carbonBlue70,
    linkSecondary: carbonBlue70,
    linkInverse: carbonBlue40,
    linkInverseHover: carbonBlue30,
    linkInverseActive: carbonGray10,
    linkVisited: carbonPurple60,
    linkInverseVisited: carbonPurple40,
    iconPrimary: carbonGray10,
    iconSecondary: carbonGray70,
    iconOnColor: carbonWhite,
    iconOnColorDisabled: carbonGray50,
    iconInteractive: carbonBlue60,
    iconInverse: carbonWhite,
    iconDisabled: Color.fromRGBO(
      22,
      22,
      22,
      .25,
    ), // carbonGray100 with 25% opacity
    supportError: carbonRed60,
    supportSuccess: carbonGreen50,
    supportWarning: carbonYellow30,
    supportInfo: carbonBlue70,
    supportErrorInverse: carbonRed50,
    supportSuccessInverse: carbonGreen40,
    supportWarningInverse: carbonYellow30,
    supportInfoInverse: carbonBlue50,
    supportCautionMajor: carbonOrange40,
    supportCautionMinor: carbonYellow30,
    supportUndefined: carbonPurple60,
    focus: carbonBlue60,
    focusInset: carbonWhite,
    focusInverse: carbonWhite,
    buttonPrimary: carbonBlue60,
    buttonPrimaryHover: carbonBlueHover60,
    buttonPrimaryActive: carbonBlue80,
    buttonSecondary: carbonGray80,
    buttonSecondaryHover: carbonGrayHover80,
    buttonSecondaryActive: carbonGray60,
    buttonTertiary: carbonBlue60,
    buttonTertiaryHover: carbonBlueHover60,
    buttonTertiaryActive: carbonBlue80,
    buttonDangerPrimary: carbonRed60,
    buttonDangerSecondary: carbonRed60,
    buttonDangerHover: carbonRedHover60,
    buttonDangerActive: carbonRed80,
    buttonSeparator: carbonGray20,
    buttonDisabled: carbonGray30,
    interactive: carbonBlue60,
    highlight: carbonBlue20,
    overlay: Color.fromRGBO(22, 22, 22, .50), // carbonGray100 with 50% opacity
    skeletonBackground: carbonGrayHover10,
    skeletonElement: carbonGray30,
    toggleOff: carbonGray50,
    tagBackgroundGray: carbonGray20,
    tagColorGray: carbonGray100,
    tagHoverGray: carbonGrayHover20,
    tagBorderGray: carbonGray40,
    tagBackgroundCoolGray: carbonCoolGray20,
    tagColorCoolGray: carbonCoolGray100,
    tagHoverCoolGray: carbonCoolGrayHover20,
    tagBorderCoolGray: carbonCoolGray40,
    tagBackgroundWarmGray: carbonWarmGray20,
    tagColorWarmGray: carbonWarmGray100,
    tagHoverWarmGray: carbonWarmGrayHover20,
    tagBorderWarmGray: carbonWarmGray40,
    tagBackgroundRed: carbonRed20,
    tagColorRed: carbonRed70,
    tagHoverRed: carbonRedHover20,
    tagBorderRed: carbonRed40,
    tagBackgroundMagenta: carbonMagenta20,
    tagColorMagenta: carbonMagenta70,
    tagHoverMagenta: carbonMagentaHover20,
    tagBorderMagenta: carbonMagenta40,
    tagBackgroundPurple: carbonPurple20,
    tagColorPurple: carbonPurple70,
    tagHoverPurple: carbonPurpleHover20,
    tagBorderPurple: carbonPurple40,
    tagBackgroundBlue: carbonBlue20,
    tagColorBlue: carbonBlue70,
    tagHoverBlue: carbonBlueHover20,
    tagBorderBlue: carbonBlue40,
    tagBackgroundCyan: carbonCyan20,
    tagColorCyan: carbonCyan70,
    tagHoverCyan: carbonCyanHover20,
    tagBorderCyan: carbonCyan40,
    tagBackgroundTeal: carbonTeal20,
    tagColorTeal: carbonTeal70,
    tagHoverTeal: carbonTealHover20,
    tagBorderTeal: carbonTeal40,
    tagBackgroundGreen: carbonGreen20,
    tagColorGreen: carbonGreen70,
    tagHoverGreen: carbonGreenHover20,
    tagBorderGreen: carbonGreen40,
  );

  static const gray100 = CarbonColorTokens(
    background: carbonGray100,
    backgroundHover: Color.fromRGBO(
      141,
      141,
      141,
      .16,
    ), // carbonGray50 with 16% opacity
    backgroundActive: Color.fromRGBO(
      141,
      141,
      141,
      .40,
    ), // carbonGray50 with 40% opacity
    backgroundSelected: Color.fromRGBO(
      141,
      141,
      141,
      .24,
    ), // carbonGray50 with 24% opacity
    backgroundSelectedHover: Color.fromRGBO(
      141,
      141,
      141,
      .32,
    ), // carbonGray50 with 32% opacity
    backgroundInverse: carbonGray10,
    backgroundInverseHover: carbonGrayHover10,
    backgroundBrand: carbonBlue60,
    layer01: carbonGray90,
    layer02: carbonGray80,
    layer03: carbonGray70,
    layerHover01: carbonGrayHover90,
    layerHover02: carbonGrayHover80,
    layerHover03: carbonGrayHover70,
    layerActive01: carbonGray70,
    layerActive02: carbonGray60,
    layerActive03: carbonGray50,
    layerSelected01: carbonGray80,
    layerSelected02: carbonGray70,
    layerSelected03: carbonGray60,
    layerSelectedHover01: carbonGrayHover80,
    layerSelectedHover02: carbonGrayHover70,
    layerSelectedHover03: carbonGrayHover60,
    layerSelectedInverse: carbonGray10,
    layerSelectedDisabled: carbonGray60,
    layerAccent01: carbonGray80,
    layerAccent02: carbonGray70,
    layerAccent03: carbonGray60,
    layerAccentHover01: carbonGrayHover80,
    layerAccentHover02: carbonGrayHover70,
    layerAccentHover03: carbonGrayHover60,
    layerAccentActive01: carbonGray70,
    layerAccentActive02: carbonGray50,
    layerAccentActive03: carbonGray80,
    field01: carbonGray90,
    field02: carbonGray80,
    field03: carbonGray70,
    fieldHover01: carbonGrayHover90,
    fieldHover02: carbonGrayHover80,
    fieldHover03: carbonGrayHover70,
    borderInteractive: carbonBlue50,
    borderSubtle00: carbonGray70,
    borderSubtle01: carbonGray70,
    borderSubtle02: carbonGray60,
    borderSubtle03: carbonGray50,
    borderSubtleSelected01: carbonGray60,
    borderSubtleSelected02: carbonGray50,
    borderSubtleSelected03: carbonGray40,
    borderStrong01: carbonGray60,
    borderStrong02: carbonGray50,
    borderStrong03: carbonGray40,
    borderTitle01: carbonGray70,
    borderTitle02: carbonGray60,
    borderTitle03: carbonGray50,
    borderInverse: carbonGray10,
    borderDisabled: Color.fromRGBO(
      141,
      141,
      141,
      .50,
    ), // carbonGray50 with 50% opacity
    textPrimary: carbonGray10,
    textSecondary: carbonGray30,
    textPlaceholder: carbonGray60,
    textOnColor: carbonWhite,
    textOnColorDisabled: Color.fromRGBO(
      255,
      255,
      255,
      .25,
    ), // carbonWhite with 25% opacity
    textHelper: carbonGray50,
    textError: carbonRed40,
    textInverse: carbonGray100,
    textDisabled: Color.fromRGBO(
      244,
      244,
      244,
      .25,
    ), // carbonGray10 with 25% opacity
    linkPrimary: carbonBlue40,
    linkPrimaryHover: carbonBlue30,
    linkSecondary: carbonBlue30,
    linkInverse: carbonBlue60,
    linkInverseHover: carbonBlue70,
    linkInverseActive: carbonGray100,
    linkVisited: carbonPurple40,
    linkInverseVisited: carbonPurple60,
    iconPrimary: carbonGray10,
    iconSecondary: carbonGray30,
    iconOnColor: carbonWhite,
    iconOnColorDisabled: carbonGray60,
    iconInteractive: carbonWhite,
    iconInverse: carbonGray100,
    iconDisabled: Color.fromRGBO(
      244,
      244,
      244,
      .25,
    ), // carbonGray10 with 25% opacity
    supportError: carbonRed50,
    supportSuccess: carbonGreen40,
    supportWarning: carbonYellow30,
    supportInfo: carbonBlue50,
    supportErrorInverse: carbonRed60,
    supportSuccessInverse: carbonGreen50,
    supportWarningInverse: carbonYellow30,
    supportInfoInverse: carbonBlue70,
    supportCautionMajor: carbonOrange40,
    supportCautionMinor: carbonYellow30,
    supportUndefined: carbonPurple50,
    focus: carbonWhite,
    focusInset: carbonGray100,
    focusInverse: carbonBlue60,
    buttonPrimary: carbonBlue60,
    buttonPrimaryHover: carbonBlueHover60,
    buttonPrimaryActive: carbonBlue80,
    buttonSecondary: carbonGray60,
    buttonSecondaryHover: carbonGrayHover60,
    buttonSecondaryActive: carbonGray80,
    buttonTertiary: carbonWhite,
    buttonTertiaryHover: carbonGray10,
    buttonTertiaryActive: carbonGray30,
    buttonDangerPrimary: carbonRed60,
    buttonDangerSecondary: carbonRed50,
    buttonDangerHover: carbonRedHover60,
    buttonDangerActive: carbonRed80,
    buttonSeparator: carbonGray100,
    buttonDisabled: carbonGray70,
    interactive: carbonBlue50,
    highlight: carbonBlue90,
    overlay: Color.fromRGBO(22, 22, 22, .70), // carbonGray100 with 70% opacity
    skeletonBackground: carbonGrayHover80,
    skeletonElement: carbonGray70,
    toggleOff: carbonGray60,
    tagBackgroundGray: carbonGray70,
    tagColorGray: carbonGray20,
    tagHoverGray: carbonGrayHover70,
    tagBorderGray: carbonGray50,
    tagBackgroundCoolGray: carbonCoolGray70,
    tagColorCoolGray: carbonCoolGray20,
    tagHoverCoolGray: carbonCoolGrayHover70,
    tagBorderCoolGray: carbonCoolGray50,
    tagBackgroundWarmGray: carbonWarmGray70,
    tagColorWarmGray: carbonWarmGray20,
    tagHoverWarmGray: carbonWarmGrayHover70,
    tagBorderWarmGray: carbonWarmGray50,
    tagBackgroundRed: carbonRed70,
    tagColorRed: carbonRed20,
    tagHoverRed: carbonRedHover70,
    tagBorderRed: carbonRed50,
    tagBackgroundMagenta: carbonMagenta70,
    tagColorMagenta: carbonMagenta20,
    tagHoverMagenta: carbonMagentaHover70,
    tagBorderMagenta: carbonMagenta50,
    tagBackgroundPurple: carbonPurple70,
    tagColorPurple: carbonPurple20,
    tagHoverPurple: carbonPurpleHover70,
    tagBorderPurple: carbonPurple50,
    tagBackgroundBlue: carbonBlue70,
    tagColorBlue: carbonBlue20,
    tagHoverBlue: carbonBlueHover70,
    tagBorderBlue: carbonBlue50,
    tagBackgroundCyan: carbonCyan70,
    tagColorCyan: carbonCyan20,
    tagHoverCyan: carbonCyanHover70,
    tagBorderCyan: carbonCyan50,
    tagBackgroundTeal: carbonTeal70,
    tagColorTeal: carbonTeal20,
    tagHoverTeal: carbonTealHover70,
    tagBorderTeal: carbonTeal50,
    tagBackgroundGreen: carbonGreen70,
    tagColorGreen: carbonGreen20,
    tagHoverGreen: carbonGreenHover70,
    tagBorderGreen: carbonGreen50,
  );

  static ThemeData buildLightTheme() {
    return ThemeData(
      textTheme: carbonTextTheme(carbonGray100),
      colorScheme: ColorScheme.light(
        brightness: Brightness.light,
        primary: carbonBlue60,
        // primary: carbonTheme.buttonPrimary,
        onPrimary: carbonWhite,
        secondary: carbonGray90,
        onSecondary: carbonWhite,
        error: carbonRed60,
        onError: carbonWhite,
        surface: carbonWhite,
        onSurface: carbonGray90,
      ),
      extensions: <ThemeExtension<dynamic>>[CarbonTokens.white],
      useMaterial3: true,
    );
  }

  static ThemeData buildDarkTheme() {
    return ThemeData(
      textTheme: carbonTextTheme(carbonGray100),
      colorScheme: ColorScheme.dark(
        brightness: Brightness.dark,
        primary: carbonBlue60,
        onPrimary: carbonWhite,
        secondary: carbonGray90,
        onSecondary: carbonWhite,
        error: carbonRed60,
        onError: carbonWhite,
        surface: carbonGray100,
        onSurface: carbonGray10,
      ),
      extensions: <ThemeExtension<dynamic>>[CarbonTokens.gray100],
      useMaterial3: true,
    );
  }
}
